### ISSUE TITLE
Scala 2.12 compatible release

### ISSUE THREAD

**Issue by cory-p-oncota** [kamon-io/kamon-fluentd#1]
Current blockers
```
fluent-scala-logger
~~fluentd-standalone~~
```

I have a branch for fluent-scala-logger ready to go once this is resolved and we have a release:
https://github.com/xerial/fluentd-standalone/pull/3

**Comment by cory-p-oncota** [comment]
~~fluentd-standalone~~

Will try to get fluent-scala-logger rolling hopefully a PR here soon.

**Comment by jCalamari** [comment]
Hi, any update on this issue?

**Comment by nvollmar** [comment]
still blocking our upgrade to scala 2.12

**Comment by spaced** [comment]
What has to be done? can i help? because xerial/fluentd-standalone#3 is merged.

**Comment by spaced** [comment]
It would be great if a version 0.6.5 (on par with current Kamon core which is available for Scala 2.12) was released, and published to Maven Central.

**Comment by dpsoft** [comment]
@spaced I've just published the `0.6.5` version in our bintray repository (https://bintray.com/kamon-io/releases)
